# Generated by Django 3.1.1 on 2020-09-19 18:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=50)),
                ('definition', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('language_code', models.CharField(max_length=10)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'glossaries',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='DefinitonTermVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('definition', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_variations', to='wagtail_glossary.definition')),
            ],
        ),
        migrations.AddField(
            model_name='definition',
            name='glossary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='wagtail_glossary.glossary'),
        ),
    ]
